apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: emissary-ingress
  namespace: emissary
spec:
  endpoints:
    - scheme: http
      port: ambassador-admin
      scrape_interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: emissary-ingress
      app.kubernetes.io/part-of: emissary-ingress
      service: ambassador-admin
  namespaceSelector:
    matchNames:
      - emissary
