apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-to-workflow-defaul
  namespace: argo
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
roleRef:
  kind: Role
  name: executor
  apiGroup: rbac.authorization.k8s.io
