apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflowClusterExecutor
rules:
# argo apis
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
      - get
      - list
      - watch
      - delete
  # k8s standard APIs
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch