apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: dmz
spec:
  image: 
    tag: "v1.92.1"
  selectAllByDefault: true
  replicaCount: 1
  remoteWrite:
    - url: "http://victoria-metrics.kinnovatio.local:8429/api/v1/write"  # Replace with the URL of your central Victoria Metrics service
