apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: dmz
spec:
  image: 
    tag: "v1.93.0"
  selectAllByDefault: true
  replicaCount: 1
  externalLabels:
    clusterId: "dmz"
  remoteWrite:
    - url: "http://victoria-metrics.kinnovatio.local/api/v1/write"  # Replace with the URL of your central Victoria Metrics service
