apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- argocd-namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.0/manifests/install.yaml

patchesStrategicMerge:
- argocd-cm-overrides.configmap.yaml
- argocd-cmd-params-cm-overrides.configmap.yaml
