apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: dev
spec:
  retentionPeriod: "12d"
  storage:
    resources:
      requests:
        storage: 20Gi
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
