apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: dev
spec:
  selectAllByDefault: true
  replicaCount: 1
  externalLabels:
    clusterId: "dev"
  remoteWrite:
    - url: "http://vmsingle-dev.victoria-metrics:8429/api/v1/write"
