apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: dev
spec:
  image: 
    tag: "v1.92.1"
  selectAllByDefault: true
  replicaCount: 1
  remoteWrite:
    - url: "http://vmsingle-dev.victoria-metrics:8429/api/v1/write"
