apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: dev
spec:
#  image:
#    tag: "v1.93.3"
  retentionPeriod: "15w"
  removePvcAfterDelete: true
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi 
