apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: containers
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  tail:
    tag: kube.*
    path: /var/log/containers/*.log
    # Exclude logs from util pod
    # excludePath: /var/log/containers/utils_default_utils-*.log
    parser: cri 
    refreshIntervalSeconds: 10
    memBufLimit: 20MB
    skipLongLines: true
    db: /fluent-bit/tail/pos.db
    dbSync: Normal