apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: cadvisor-metrics
spec:
  scheme: "https"
  path: /metrics/cadvisor
  tlsConfig:
    insecureSkipVerify: true
    caFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
  # Override job label
  relabelConfigs:
    - targetLabel: job
      replacement: "kubernetes-nodes-cadvisor"
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
  
  # relabel metrics to work with Grafana dashboard
  metricRelabelConfigs:
    - action: replace
      sourceLabels: [pod]
      regex: "(.+)"
      targetLabel: pod_name
      replacement: "$1"
    - action: replace
      sourceLabels: [container]
      regex: "(.+)"
      targetLabel: container_name
      replacement: "$1"
    - action: replace
      targetLabel: name
      replacement: "k8s_stub"
    - action: replace
      sourceLabels: [id]
      regex: "^/system\\.slice/(.+)\\.service$"
      targetLabel: systemd_service_name
      replacement: "$1"