apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: node-metrics
spec:
  scheme: https
  tlsConfig:
    insecureSkipVerify: true
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  
  # relabel metrics to work with Grafana dashboard
  relabelConfigs:
    - targetLabel: job
      replacement: "kubernetes-nodes"
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)