apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: prometheus-pushgateway-ui-localhost
spec:
  hostname: 'pushgateway.localhost'
  prefix: /
  service: http://prometheus-pushgateway:9091