apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
spec:
#  image:
#    tag: "v1.93.3"
  selectAllByDefault: true
  replicaCount: 1
  externalLabels:
    clusterId: "dev"
  remoteWrite:
    - url: "http://vmsingle-vmsingle.victoria-metrics:8429/api/v1/write"
