apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-services
spec:
  generators:
  - git:
      repoURL: https://github.com/kjetilh33/infra-services.git
      revision: HEAD
      directories:
      - path: 3-k8-setup-core/*/overlays/local
      - path: 4-k8-setup-extended/*/overlays/local
  template:
    metadata:
      name: '{{path.basenameNormalized}}'
    spec:
      project: dev-services
      source:
        repoURL: https://github.com/kjetilh33/infra-services.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
#        namespace: '{{path.basenameNormalized}}'
      syncPolicy:
        automated:
          prune: true
          allowEmpty: true
        syncOptions:
          - "applyOutOfSyncOnly=false"
          - "PrunePropagationPolicy=foreground"
          - "ServerSideApply=true"