apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: argocd-server-cli
  namespace: argocd
spec:
  hostname: argocd.localhost:443
  prefix: /
  service: argocd-server:80
  regex_headers:
    Content-Type: "^application/grpc.*$"
  grpc: true