apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: gateway-helm-crd
chartName: gateway-helm-crd
namespace: envoy-gateway-system
releaseName: gateway-helm-crd
repo: https://docker.io/envoyproxy
version: v1.7.1
valuesFile: values-crd.yaml